SELECT
*
FROM ADMINISTRACAO.EMPREGADO 
CROSS JOIN ADMINISTRACAO.DEPARTAMENTO

CREATE SCHEMA TESTE
CREATE TABLE TESTE.NUMERO (
	Num TINYINT
)

INSERT INTO TESTE.NUMERO VALUES(1)
INSERT INTO TESTE.NUMERO VALUES(2)
INSERT INTO TESTE.NUMERO VALUES(3)
INSERT INTO TESTE.NUMERO VALUES(4)
INSERT INTO TESTE.NUMERO VALUES(5)
INSERT INTO TESTE.NUMERO VALUES(6)
INSERT INTO TESTE.NUMERO VALUES(7)
INSERT INTO TESTE.NUMERO VALUES(8)
INSERT INTO TESTE.NUMERO VALUES(9)
INSERT INTO TESTE.NUMERO VALUES(10)

DELETE TESTE.NUMERO

SELECT N1.Num as 'num1', N2.Num as 'num2'
FROM 
TESTE.NUMERO as N1 
CROSS JOIN 
TESTE.NUMERO as N2
WHERE N1.Num BETWEEN 1 AND 2 
AND
N2.Num BETWEEN 1 AND 5



SELECT E.Pnome +' '+ E.Mnome +' '+ E.Unome AS 'Nome Completo',
D.Dnome
FROM
ADMINISTRACAO.EMPREGADO AS E
JOIN
ADMINISTRACAO.DEPARTAMENTO AS D
ON (E.Dnum = D.Dnumero);


SELECT
E.Pnome +' '+ E.Mnome +' '+ E.Unome AS 'Nome Completo',
D.Nome_dep
FROM
ADMINISTRACAO.EMPREGADO AS E 
JOIN
ADMINISTRACAO.DEPENDENTE AS D
ON (E.CPF = D.ECPF);

SELECT
D.Dnome, D.Dnumero
FROM
ADMINISTRACAO.DEPARTAMENTO AS D 
JOIN
ADMINISTRACAO.DEPTO_LOCAL AS DL
ON (D.Dnumero = DL.Dnumero)
WHERE DL.Dlocal IN ('HOUSTON', 'SUGARLAND');


SELECT
T.Pno, T.Horas
FROM 
ADMINISTRACAO.TRABALHA_EM AS T
JOIN
ADMINISTRACAO.EMPREGADO AS E
ON (E.CPF = T.ECPF)
WHERE E.Pnome = 'JOHN';


SELECT
*
FROM
ADMINISTRACAO.DEPARTAMENTO AS D
JOIN
ADMINISTRACAO.DEPTO_LOCAL AS DL
ON(D.Dnumero = DL.Dnumero)
WHERE D.Dnome = 'PESQUISA' OR D.DNOME = 'ADMINISTRAÇÃO';


SELECT
E.Pnome +' '+ E.Mnome +' '+ E.Unome AS 'Nome Completo',
D.Nome_dep
FROM
ADMINISTRACAO.EMPREGADO AS E 
LEFT JOIN
ADMINISTRACAO.DEPENDENTE AS D
ON (E.CPF = D.ECPF);


/*AC*/
SELECT
E.Pnome +' '+ E.Mnome +' '+ E.Unome AS 'Nome', D.Dnome, P.Pnome
FROM
ADMINISTRACAO.EMPREGADO AS E JOIN
ADMINISTRACAO.DEPARTAMENTO AS D 
ON (E.Dnum = D.Dnumero) JOIN
ADMINISTRACAO.PROJETO AS P
ON(D.Dnumero = P.Dnum)

