# Generated by Django 2.0.3 on 2018-04-25 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='endereco',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Endereco'),
            preserve_default=False,
        ),
    ]
